site_name: PyAwaitable
site_url: https://awaitable.zintensity.dev
repo_url: https://github.com/ZeroIntensity/pyawaitable
repo_name: ZeroIntensity/pyawaitable

nav:
    - Home: index.md
    - Overview: overview.md
    - Awaiting Coroutines: adding_coros.md
    - Callbacks: callbacks.md
    - Storing and Fetching Values: storing_and_fetching.md

theme: readthedocs

markdown_extensions:
    - admonition

plugins:
    - search
