site_name: PyAwaitable
site_url: https://awaitable.zintensity.dev
repo_url: https://github.com/ZeroIntensity/pyawaitable
repo_name: ZeroIntensity/pyawaitable

nav:
    - Home: index.md
    - Overview: overview.md
    - Awaiting Coroutines: adding_coros.md
    - Callbacks: callbacks.md
    - Storing and Fetching Values: storing_and_fetching.md

theme:
    name: material
    palette:
        - media: "(prefers-color-scheme)"
          primary: grey
          accent: light blue
          toggle:
              icon: material/brightness-auto
              name: Switch to light mode

        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: grey
          accent: light blue
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: grey
          accent: light blue
          toggle:
              icon: material/brightness-4
              name: Switch to system preference
    features:
        - content.tabs.link

    icon:
        repo: fontawesome/brands/github
markdown_extensions:
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.tabbed:
          alternate_style: true

plugins:
    - search
