site_name: PyAwaitable
site_url: https://awaitable.zintensity.dev
repo_url: https://github.com/ZeroIntensity/pyawaitable
repo_name: ZeroIntensity/pyawaitable

nav:
    - Home: index.md

theme: readthedocs

markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - admonition
    - pymdownx.details
    - pymdownx.tabbed:
          alternate_style: true
plugins:
    - search
