name: Feature
description: Suggest a new idea.
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        # Proposing a new feature to PyAwaitable

        Proposals should generally try to not make breaking changes.
  - type: textarea
    attributes:
      label: "Proposal:"
      description: >
        Outline your idea and why it would be a good idea for PyAwaitable. Make sure to include an example API for what this would look like if implemented.
      value: |
        ```c
        // Example API
        ```
    validations:
      required: true
